### PR TITLE
rewrite tests more clearly

### PR DESCRIPTION
**Pull request by webdesus**
While I only found time to look the tests

### CODE REVIEW

**Comment by webdesus** [comment]
And plz set this options to true for me. in your pull request image

**Comment by iPersona** [comment]
The option was already set to true. I uncheck it and check it again, is it ok now?
or something else I should do to enable it ?

**Comment by webdesus** [comment]
So strange.... I for some reason not can push in your pull request😔

**Comment by webdesus** [comment]
image

**Comment by webdesus** [comment]
thanks)))

**Comment by iPersona** [comment]
I merged your pr, is that ok now?

**Comment by iPersona** [comment]
you are welcome :grin:

**Pull request merged**
